### ISSUE TITLE
Might want to consider supporting setting ciphers for TlsConfigProvider

### ISSUE THREAD

**Issue by chrisrohr** [kiwiproject/dropwizard-config-providers#109]
Currently the TlsConfigProvider supports keystore path/password/type, truststore path/password/type, and supported protocols.  We should add in support for setting and excluding supported cipher suites so that this can be customized through a provider.

**Comment by sleberknight** [comment]
In order to properly support this, we will need to add `supportedCiphers` to `TlsContextConfiguration` in kiwi. The following are the things that we currently do _not_ support in `TlsContextConfiguration` which _are_ supported in Dropwizard's `TlsConfiguration`:

* `certAlias`
* `keyStoreProvider`
* `provider`
* `supportedCiphers`
* `trustSelfSignedCertificates`
* `trustStoreProvider`

To support each one of these in `TlsConfigProvider`, we would need to support our three "standard" provider mechanisms: system property, environment variable, and external property (in a properties file). This would add a lot of code. We could start be only adding `supportedCiphers` since we currently don't use any of the other ones.

**Comment by sleberknight** [comment]
kiwi 2.6.0 will contain support for `supportedCiphers` in `TlsContextConfiguration`, along with all the other properties from Dropwizard `TlsConfiguration`.

See https://github.com/kiwiproject/kiwi/issues/940
